import type {
  Lead, Customer, Job, Quote, Invoice, Payment, FollowUpTask,
  QuickBooksSyncStatus, BusinessSettings, AppState
} from './types';

// ─── Customers ─────────────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    name: 'John Martinez',
    phone: '(555) 301-4821',
    email: 'john.martinez@email.com',
    address: '142 Oakwood Drive, Springfield, IL 62701',
    source: 'Google Ads',
    totalSpent: 3200,
    lastJobDate: '2026-04-18',
    openBalance: 0,
    status: 'VIP',
    notes: 'Prefers afternoon appointments. Has a Lennox AC unit installed 2024.',
    createdDate: '2024-06-12',
    qbCustomerId: 'qb-c-001',
  },
  {
    id: 'cust-002',
    name: 'Sarah Thompson',
    phone: '(555) 874-3302',
    email: 'sarah.t@gmail.com',
    address: '89 Maple Court, Springfield, IL 62702',
    source: 'Referral',
    totalSpent: 1800,
    lastJobDate: '2026-03-05',
    openBalance: 320,
    status: 'Active',
    notes: 'Referred by John Martinez. Has rental property too.',
    createdDate: '2024-09-28',
    qbCustomerId: 'qb-c-002',
  },
  {
    id: 'cust-003',
    name: 'Robert Wilson',
    phone: '(555) 643-0971',
    email: 'rwilson@outlook.com',
    address: '2201 Elmwood Ave, Springfield, IL 62703',
    source: 'Nextdoor',
    totalSpent: 4500,
    lastJobDate: '2026-04-30',
    openBalance: 0,
    status: 'VIP',
    notes: 'Long time customer. Does annual HVAC maintenance contract.',
    createdDate: '2023-11-15',
    qbCustomerId: 'qb-c-003',
  },
  {
    id: 'cust-004',
    name: 'Linda Chen',
    phone: '(555) 229-5563',
    email: 'linda.chen@email.com',
    address: '417 Birch Lane, Springfield, IL 62704',
    source: 'Website',
    totalSpent: 950,
    lastJobDate: '2026-02-14',
    openBalance: 0,
    status: 'Active',
    notes: 'Condo owner. Limited access on weekdays.',
    createdDate: '2025-02-10',
    qbCustomerId: 'qb-c-004',
  },
  {
    id: 'cust-005',
    name: 'David Brown',
    phone: '(555) 788-2244',
    email: 'd.brown@yahoo.com',
    address: '563 Walnut Street, Springfield, IL 62705',
    source: 'Google Ads',
    totalSpent: 2100,
    lastJobDate: '2026-01-22',
    openBalance: 475,
    status: 'Active',
    notes: 'Old ductwork, may need full replacement soon.',
    createdDate: '2025-01-08',
    qbCustomerId: 'qb-c-005',
  },
  {
    id: 'cust-006',
    name: 'Jennifer Garcia',
    phone: '(555) 512-9087',
    email: 'jgarcia@email.com',
    address: '78 Pinecrest Drive, Springfield, IL 62706',
    source: 'Facebook',
    totalSpent: 750,
    lastJobDate: '2026-04-02',
    openBalance: 750,
    status: 'Active',
    notes: 'New build, first service call was leaky faucet.',
    createdDate: '2026-03-20',
  },
  {
    id: 'cust-007',
    name: 'Michael Davis',
    phone: '(555) 334-6601',
    email: 'mdavis@gmail.com',
    address: '1105 Cedar Blvd, Springfield, IL 62701',
    source: 'Yelp',
    totalSpent: 1400,
    lastJobDate: '2026-03-18',
    openBalance: 0,
    status: 'Active',
    notes: 'Electrical panel upgrade completed. May want generator install.',
    createdDate: '2025-07-14',
    qbCustomerId: 'qb-c-007',
  },
  {
    id: 'cust-008',
    name: 'Patricia Anderson',
    phone: '(555) 901-4423',
    email: 'p.anderson@email.com',
    address: '330 Sycamore Court, Springfield, IL 62702',
    source: 'Referral',
    totalSpent: 3800,
    lastJobDate: '2026-04-25',
    openBalance: 0,
    status: 'VIP',
    notes: 'Referred 3 neighbors. Always pays same day. Gold star customer.',
    createdDate: '2024-03-01',
    qbCustomerId: 'qb-c-008',
  },
];

// ─── Leads ─────────────────────────────────────────────────────────────────────

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    name: 'Carlos Mendez',
    phone: '(555) 447-8831',
    email: 'carlos.m@email.com',
    address: '209 Hillside Ave, Springfield, IL 62703',
    source: 'Google Ads',
    serviceRequested: 'AC Installation',
    estimatedValue: 3500,
    status: 'New',
    assignedTo: 'Tom Baker',
    createdDate: '2026-05-10',
    followUpDate: '2026-05-13',
    notes: 'Looking to replace 15-year-old unit before summer.',
    estimatedBudget: '$3,000–$5,000',
    preferredContactTime: 'Evenings after 6pm',
    message: 'My AC stopped working and I need a full replacement.',
  },
  {
    id: 'lead-002',
    name: 'Angela Reyes',
    phone: '(555) 673-2201',
    email: 'angela.reyes@gmail.com',
    address: '54 River Road, Springfield, IL 62704',
    source: 'Website',
    serviceRequested: 'Plumbing – Water Heater',
    estimatedValue: 1200,
    status: 'Contacted',
    assignedTo: 'Dave Williams',
    createdDate: '2026-05-07',
    followUpDate: '2026-05-14',
    notes: 'Water heater making loud noise. Spoke with her Tuesday.',
    estimatedBudget: '$1,000–$1,500',
    preferredContactTime: 'Mornings',
  },
  {
    id: 'lead-003',
    name: 'Thomas Hill',
    phone: '(555) 280-5542',
    email: 'tomhill@outlook.com',
    address: '1420 Oak Street, Springfield, IL 62706',
    source: 'Nextdoor',
    serviceRequested: 'Electrical Panel Upgrade',
    estimatedValue: 2800,
    status: 'Quoted',
    assignedTo: 'Tom Baker',
    createdDate: '2026-04-28',
    followUpDate: '2026-05-15',
    notes: 'Quote sent. 200-amp upgrade. Following up on acceptance.',
    estimatedBudget: '$2,500–$3,500',
    preferredContactTime: 'Anytime',
  },
  {
    id: 'lead-004',
    name: 'Monica Patterson',
    phone: '(555) 119-8844',
    email: 'mpatterson@email.com',
    address: '87 Lakeview Terrace, Springfield, IL 62701',
    source: 'Referral',
    serviceRequested: 'Furnace Replacement',
    estimatedValue: 4200,
    status: 'Scheduled',
    assignedTo: 'Dave Williams',
    createdDate: '2026-04-20',
    followUpDate: '2026-05-20',
    notes: 'Referred by Robert Wilson. Scheduled for May 20.',
    estimatedBudget: '$4,000–$5,000',
    preferredContactTime: 'Afternoons',
  },
  {
    id: 'lead-005',
    name: 'Kevin Nguyen',
    phone: '(555) 762-0033',
    email: 'knguyen@gmail.com',
    address: '2003 Pineview Dr, Springfield, IL 62705',
    source: 'Facebook',
    serviceRequested: 'HVAC Tune-Up',
    estimatedValue: 350,
    status: 'Won',
    assignedTo: 'Tom Baker',
    createdDate: '2026-04-10',
    followUpDate: '2026-05-10',
    notes: 'Converted to customer. Annual tune-up completed.',
  },
  {
    id: 'lead-006',
    name: 'Sandra Lee',
    phone: '(555) 399-7712',
    email: 's.lee@email.com',
    address: '612 Sunset Blvd, Springfield, IL 62702',
    source: 'Google Ads',
    serviceRequested: 'Plumbing – Drain Cleaning',
    estimatedValue: 280,
    status: 'Lost',
    assignedTo: 'Dave Williams',
    createdDate: '2026-04-05',
    followUpDate: '2026-04-12',
    notes: 'Went with a competitor. Price was $50 cheaper.',
  },
  {
    id: 'lead-007',
    name: 'Brian Foster',
    phone: '(555) 545-1129',
    email: 'bfoster@yahoo.com',
    address: '38 Wildwood Lane, Springfield, IL 62703',
    source: 'Yard Sign',
    serviceRequested: 'AC Repair',
    estimatedValue: 650,
    status: 'New',
    assignedTo: 'Tom Baker',
    createdDate: '2026-05-11',
    followUpDate: '2026-05-13',
    notes: 'Saw our yard sign on Elmwood. AC not cooling properly.',
    preferredContactTime: 'Afternoons',
  },
  {
    id: 'lead-008',
    name: 'Diane Mitchell',
    phone: '(555) 882-4430',
    email: 'diane.mitch@email.com',
    address: '900 Rosewood Ave, Springfield, IL 62704',
    source: 'Yelp',
    serviceRequested: 'Whole-Home Generator',
    estimatedValue: 8500,
    status: 'Contacted',
    assignedTo: 'Mike Rodriguez',
    createdDate: '2026-05-08',
    followUpDate: '2026-05-16',
    notes: 'High value lead. Sending detailed proposal this week.',
    estimatedBudget: '$8,000–$10,000',
    preferredContactTime: 'Weekday mornings',
  },
  {
    id: 'lead-009',
    name: 'James Carter',
    phone: '(555) 223-6690',
    email: 'jcarter@gmail.com',
    address: '501 Greenfield Rd, Springfield, IL 62706',
    source: 'Website',
    serviceRequested: 'Ductwork Replacement',
    estimatedValue: 2600,
    status: 'Quoted',
    assignedTo: 'Dave Williams',
    createdDate: '2026-04-30',
    followUpDate: '2026-05-17',
    notes: 'Quote sent for complete duct replacement.',
    estimatedBudget: '$2,000–$3,000',
    preferredContactTime: 'Evenings',
  },
  {
    id: 'lead-010',
    name: 'Laura Simmons',
    phone: '(555) 670-3321',
    email: 'l.simmons@email.com',
    address: '711 Ash Street, Springfield, IL 62701',
    source: 'Nextdoor',
    serviceRequested: 'Bathroom Plumbing Remodel',
    estimatedValue: 3100,
    status: 'New',
    assignedTo: 'Dave Williams',
    createdDate: '2026-05-12',
    followUpDate: '2026-05-14',
    notes: 'Full bathroom rough-in. New construction project.',
    estimatedBudget: '$2,500–$4,000',
    preferredContactTime: 'Anytime',
  },
];

// ─── Jobs ──────────────────────────────────────────────────────────────────────

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    serviceType: 'AC Installation – Lennox XC20',
    scheduledDate: '2026-04-18',
    status: 'Completed',
    value: 3200,
    paidStatus: 'Paid',
    assignedTo: 'Tom Baker',
    notes: 'Full installation with new pad and disconnect. Customer very satisfied.',
    quoteId: 'quote-001',
  },
  {
    id: 'job-002',
    customerId: 'cust-002',
    customerName: 'Sarah Thompson',
    serviceType: 'Plumbing – Kitchen Faucet & Garbage Disposal',
    scheduledDate: '2026-03-05',
    status: 'Completed',
    value: 480,
    paidStatus: 'Partial',
    assignedTo: 'Dave Williams',
    notes: 'Replaced faucet and installed new disposal. Balance $320 still owed.',
  },
  {
    id: 'job-003',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    serviceType: 'Annual HVAC Maintenance – Spring Tune-Up',
    scheduledDate: '2026-04-30',
    status: 'Completed',
    value: 250,
    paidStatus: 'Paid',
    assignedTo: 'Tom Baker',
    notes: 'Spring tune-up, replaced filter, checked refrigerant.',
  },
  {
    id: 'job-004',
    customerId: 'cust-007',
    customerName: 'Michael Davis',
    serviceType: 'Electrical Panel Upgrade – 200 Amp',
    scheduledDate: '2026-03-18',
    status: 'Completed',
    value: 1400,
    paidStatus: 'Paid',
    assignedTo: 'Tom Baker',
    notes: 'Upgraded from 100 to 200 amp. Permit pulled.',
  },
  {
    id: 'job-005',
    customerId: 'cust-004',
    customerName: 'Linda Chen',
    serviceType: 'Plumbing – Toilet Repair',
    scheduledDate: '2026-02-14',
    status: 'Completed',
    value: 195,
    paidStatus: 'Paid',
    assignedTo: 'Dave Williams',
    notes: 'Replaced flapper and fill valve.',
  },
  {
    id: 'job-006',
    customerId: 'cust-008',
    customerName: 'Patricia Anderson',
    serviceType: 'Furnace Replacement – Carrier 96% Gas Furnace',
    scheduledDate: '2026-04-25',
    status: 'Completed',
    value: 3800,
    paidStatus: 'Paid',
    assignedTo: 'Dave Williams',
    notes: 'Full replacement, new flue liner, thermostat upgrade included.',
    quoteId: 'quote-003',
  },
  {
    id: 'job-007',
    customerId: 'cust-005',
    customerName: 'David Brown',
    serviceType: 'HVAC Inspection & Duct Sealing',
    scheduledDate: '2026-01-22',
    status: 'Completed',
    value: 620,
    paidStatus: 'Partial',
    assignedTo: 'Tom Baker',
    notes: 'Sealed major duct leaks. Balance $475 owed on invoice.',
  },
  {
    id: 'job-008',
    customerId: 'cust-006',
    customerName: 'Jennifer Garcia',
    serviceType: 'Plumbing – Leaky Faucet & Water Pressure',
    scheduledDate: '2026-04-02',
    status: 'Completed',
    value: 310,
    paidStatus: 'Unpaid',
    assignedTo: 'Dave Williams',
    notes: 'Fixed two faucets and adjusted pressure regulator. Invoice outstanding.',
  },
  {
    id: 'job-009',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    serviceType: 'Spring HVAC Maintenance',
    scheduledDate: '2026-05-15',
    status: 'Scheduled',
    value: 150,
    paidStatus: 'Unpaid',
    assignedTo: 'Tom Baker',
    notes: 'Annual spring check-up.',
  },
  {
    id: 'job-010',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    serviceType: 'Insulation – Attic Upgrade',
    scheduledDate: '2026-05-22',
    status: 'Scheduled',
    value: 1800,
    paidStatus: 'Unpaid',
    assignedTo: 'Dave Williams',
    notes: 'Blown-in insulation R-38. Pre-approved from quote.',
    quoteId: 'quote-007',
  },
];

// ─── Quotes ────────────────────────────────────────────────────────────────────

export const mockQuotes: Quote[] = [
  {
    id: 'quote-001',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    quoteDate: '2026-04-10',
    amount: 3200,
    status: 'Accepted',
    expirationDate: '2026-05-10',
    services: ['AC Installation – Lennox XC20 3-ton', 'New concrete pad', 'Disconnect upgrade'],
    notes: 'Customer accepted same day.',
  },
  {
    id: 'quote-002',
    customerId: 'cust-002',
    customerName: 'Sarah Thompson',
    quoteDate: '2026-05-01',
    amount: 2400,
    status: 'Sent',
    expirationDate: '2026-05-31',
    services: ['Water heater replacement – 50gal gas', 'Permit & inspection'],
    notes: 'Sent via email. Following up May 15.',
  },
  {
    id: 'quote-003',
    customerId: 'cust-008',
    customerName: 'Patricia Anderson',
    quoteDate: '2026-04-15',
    amount: 3800,
    status: 'Accepted',
    expirationDate: '2026-05-15',
    services: ['Carrier 96% gas furnace', 'New flue liner', 'Smart thermostat'],
    notes: 'Accepted within 48 hours.',
  },
  {
    id: 'quote-004',
    customerId: 'cust-005',
    customerName: 'David Brown',
    quoteDate: '2026-04-22',
    amount: 5800,
    status: 'Declined',
    expirationDate: '2026-05-22',
    services: ['Full ductwork replacement', 'Air handler upgrade'],
    notes: 'Customer said too expensive. Will reconsider next year.',
  },
  {
    id: 'quote-005',
    customerId: 'cust-007',
    customerName: 'Michael Davis',
    quoteDate: '2026-05-03',
    amount: 4200,
    status: 'Draft',
    expirationDate: '2026-06-03',
    services: ['Whole-home standby generator – 11kW', 'Transfer switch', 'Propane connection'],
    notes: 'Still preparing line-item breakdown.',
  },
  {
    id: 'quote-006',
    customerId: 'cust-004',
    customerName: 'Linda Chen',
    quoteDate: '2026-03-18',
    amount: 1650,
    status: 'Expired',
    expirationDate: '2026-04-18',
    services: ['Mini-split installation – 1 zone'],
    notes: 'Customer did not respond. Expired.',
  },
  {
    id: 'quote-007',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    quoteDate: '2026-05-05',
    amount: 1800,
    status: 'Accepted',
    expirationDate: '2026-06-05',
    services: ['Attic blown-in insulation – R-38', 'Air sealing'],
    notes: 'Accepted. Job scheduled for May 22.',
  },
  {
    id: 'quote-008',
    customerId: 'cust-006',
    customerName: 'Jennifer Garcia',
    quoteDate: '2026-05-09',
    amount: 890,
    status: 'Sent',
    expirationDate: '2026-06-09',
    services: ['Bathroom rough-in plumbing', 'New toilet installation'],
    notes: 'Sent Tuesday. Waiting on response.',
  },
];

// ─── Invoices ──────────────────────────────────────────────────────────────────

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'INV-2026-0041',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    invoiceDate: '2026-04-18',
    dueDate: '2026-05-18',
    amount: 3200,
    paidAmount: 3200,
    status: 'Paid',
    linkedJobId: 'job-001',
    source: 'QuickBooks',
    notes: 'Paid in full by check.',
    qbInvoiceId: 'qb-inv-041',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'INV-2026-0038',
    customerId: 'cust-002',
    customerName: 'Sarah Thompson',
    invoiceDate: '2026-03-05',
    dueDate: '2026-04-05',
    amount: 480,
    paidAmount: 160,
    status: 'Overdue',
    linkedJobId: 'job-002',
    source: 'QuickBooks',
    notes: 'Partial payment received. Balance $320 overdue.',
    qbInvoiceId: 'qb-inv-038',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'INV-2026-0044',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    invoiceDate: '2026-04-30',
    dueDate: '2026-05-30',
    amount: 250,
    paidAmount: 250,
    status: 'Paid',
    linkedJobId: 'job-003',
    source: 'QuickBooks',
    notes: 'Annual maintenance contract.',
    qbInvoiceId: 'qb-inv-044',
  },
  {
    id: 'inv-004',
    invoiceNumber: 'INV-2026-0035',
    customerId: 'cust-007',
    customerName: 'Michael Davis',
    invoiceDate: '2026-03-18',
    dueDate: '2026-04-18',
    amount: 1400,
    paidAmount: 1400,
    status: 'Paid',
    linkedJobId: 'job-004',
    source: 'QuickBooks',
    notes: 'Panel upgrade paid via card.',
    qbInvoiceId: 'qb-inv-035',
  },
  {
    id: 'inv-005',
    invoiceNumber: 'INV-2026-0031',
    customerId: 'cust-004',
    customerName: 'Linda Chen',
    invoiceDate: '2026-02-14',
    dueDate: '2026-03-14',
    amount: 195,
    paidAmount: 195,
    status: 'Paid',
    linkedJobId: 'job-005',
    source: 'CRM',
    notes: '',
  },
  {
    id: 'inv-006',
    invoiceNumber: 'INV-2026-0045',
    customerId: 'cust-008',
    customerName: 'Patricia Anderson',
    invoiceDate: '2026-04-25',
    dueDate: '2026-05-25',
    amount: 3800,
    paidAmount: 3800,
    status: 'Paid',
    linkedJobId: 'job-006',
    source: 'QuickBooks',
    notes: 'Paid same day via check.',
    qbInvoiceId: 'qb-inv-045',
  },
  {
    id: 'inv-007',
    invoiceNumber: 'INV-2026-0029',
    customerId: 'cust-005',
    customerName: 'David Brown',
    invoiceDate: '2026-01-22',
    dueDate: '2026-02-22',
    amount: 620,
    paidAmount: 145,
    status: 'Overdue',
    linkedJobId: 'job-007',
    source: 'QuickBooks',
    notes: 'Partial payment only. Customer says will pay next month.',
    qbInvoiceId: 'qb-inv-029',
  },
  {
    id: 'inv-008',
    invoiceNumber: 'INV-2026-0043',
    customerId: 'cust-006',
    customerName: 'Jennifer Garcia',
    invoiceDate: '2026-04-02',
    dueDate: '2026-05-02',
    amount: 310,
    paidAmount: 0,
    status: 'Overdue',
    linkedJobId: 'job-008',
    source: 'CRM',
    notes: 'New customer, invoice sent via email.',
  },
  {
    id: 'inv-009',
    invoiceNumber: 'INV-2026-0046',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    invoiceDate: '2026-05-12',
    dueDate: '2026-06-12',
    amount: 150,
    paidAmount: 0,
    status: 'Unpaid',
    linkedJobId: 'job-009',
    source: 'CRM',
    notes: 'Upcoming maintenance invoice.',
  },
  {
    id: 'inv-010',
    invoiceNumber: 'INV-2026-0047',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    invoiceDate: '2026-05-12',
    dueDate: '2026-06-12',
    amount: 1800,
    paidAmount: 0,
    status: 'Unpaid',
    linkedJobId: 'job-010',
    source: 'CRM',
    notes: 'Attic insulation job scheduled May 22.',
  },
];

// ─── Payments ──────────────────────────────────────────────────────────────────

export const mockPayments: Payment[] = [
  {
    id: 'pay-001',
    invoiceId: 'inv-001',
    customerId: 'cust-001',
    customerName: 'John Martinez',
    amount: 3200,
    date: '2026-04-18',
    method: 'Check',
    qbPaymentId: 'qb-pay-001',
  },
  {
    id: 'pay-002',
    invoiceId: 'inv-002',
    customerId: 'cust-002',
    customerName: 'Sarah Thompson',
    amount: 160,
    date: '2026-03-05',
    method: 'Credit Card',
    qbPaymentId: 'qb-pay-002',
  },
  {
    id: 'pay-003',
    invoiceId: 'inv-003',
    customerId: 'cust-003',
    customerName: 'Robert Wilson',
    amount: 250,
    date: '2026-04-30',
    method: 'ACH',
    qbPaymentId: 'qb-pay-003',
  },
  {
    id: 'pay-004',
    invoiceId: 'inv-004',
    customerId: 'cust-007',
    customerName: 'Michael Davis',
    amount: 1400,
    date: '2026-03-18',
    method: 'Credit Card',
    qbPaymentId: 'qb-pay-004',
  },
  {
    id: 'pay-005',
    invoiceId: 'inv-005',
    customerId: 'cust-004',
    customerName: 'Linda Chen',
    amount: 195,
    date: '2026-02-14',
    method: 'Check',
  },
  {
    id: 'pay-006',
    invoiceId: 'inv-006',
    customerId: 'cust-008',
    customerName: 'Patricia Anderson',
    amount: 3800,
    date: '2026-04-25',
    method: 'Check',
    qbPaymentId: 'qb-pay-006',
  },
  {
    id: 'pay-007',
    invoiceId: 'inv-007',
    customerId: 'cust-005',
    customerName: 'David Brown',
    amount: 145,
    date: '2026-01-22',
    method: 'Credit Card',
    qbPaymentId: 'qb-pay-007',
  },
];

// ─── Follow Ups ────────────────────────────────────────────────────────────────

export const mockFollowUps: FollowUpTask[] = [
  {
    id: 'fu-001',
    leadId: 'lead-001',
    contactName: 'Carlos Mendez',
    reason: 'Follow up on AC replacement quote',
    dueDate: '2026-05-13',
    priority: 'High',
    status: 'Pending',
    notes: 'Call to check if they want to schedule.',
  },
  {
    id: 'fu-002',
    leadId: 'lead-008',
    contactName: 'Diane Mitchell',
    reason: 'Send generator proposal',
    dueDate: '2026-05-12',
    priority: 'High',
    status: 'Pending',
    notes: 'High-value lead. Priority follow up.',
  },
  {
    id: 'fu-003',
    customerId: 'cust-002',
    contactName: 'Sarah Thompson',
    reason: 'Collect outstanding balance $320',
    dueDate: '2026-05-08',
    priority: 'High',
    status: 'Pending',
    notes: 'Invoice overdue. Called twice, left voicemail.',
  },
  {
    id: 'fu-004',
    customerId: 'cust-005',
    contactName: 'David Brown',
    reason: 'Collect overdue balance $475',
    dueDate: '2026-05-05',
    priority: 'High',
    status: 'Pending',
    notes: 'Invoice is 90 days past due.',
  },
  {
    id: 'fu-005',
    leadId: 'lead-003',
    contactName: 'Thomas Hill',
    reason: 'Panel upgrade quote acceptance check-in',
    dueDate: '2026-05-15',
    priority: 'Medium',
    status: 'Pending',
    notes: 'Quote sent April 28, expires May 28.',
  },
  {
    id: 'fu-006',
    customerId: 'cust-001',
    contactName: 'John Martinez',
    reason: 'Remind about spring tune-up appointment',
    dueDate: '2026-05-13',
    priority: 'Medium',
    status: 'Pending',
    notes: 'Job scheduled May 15. Confirm appointment.',
  },
  {
    id: 'fu-007',
    customerId: 'cust-008',
    contactName: 'Patricia Anderson',
    reason: 'Thank you call + ask for referral',
    dueDate: '2026-05-02',
    priority: 'Low',
    status: 'Completed',
    notes: 'Called and thanked. She referred her neighbor Lisa.',
  },
  {
    id: 'fu-008',
    leadId: 'lead-002',
    contactName: 'Angela Reyes',
    reason: 'Water heater quote follow-up',
    dueDate: '2026-05-14',
    priority: 'Medium',
    status: 'Pending',
    notes: 'Quote not yet sent. Book inspection first.',
  },
];

// ─── Monthly Revenue (for charts) ─────────────────────────────────────────────

export const monthlyRevenue = [
  { month: 'Jun', revenue: 6800 },
  { month: 'Jul', revenue: 9200 },
  { month: 'Aug', revenue: 10400 },
  { month: 'Sep', revenue: 8700 },
  { month: 'Oct', revenue: 7100 },
  { month: 'Nov', revenue: 5300 },
  { month: 'Dec', revenue: 4900 },
  { month: 'Jan', revenue: 4100 },
  { month: 'Feb', revenue: 5600 },
  { month: 'Mar', revenue: 7800 },
  { month: 'Apr', revenue: 9600 },
  { month: 'May', revenue: 5350 },
];

export const leadSourceData = [
  { name: 'Google Ads', value: 35 },
  { name: 'Referral', value: 22 },
  { name: 'Website', value: 18 },
  { name: 'Nextdoor', value: 12 },
  { name: 'Facebook', value: 8 },
  { name: 'Other', value: 5 },
];

// ─── Initial App State ─────────────────────────────────────────────────────────

export const initialAppState: AppState = {
  leads: mockLeads,
  customers: mockCustomers,
  jobs: mockJobs,
  quotes: mockQuotes,
  invoices: mockInvoices,
  payments: mockPayments,
  followUps: mockFollowUps,
  quickBooksSync: {
    connected: false,
    lastSyncDate: null,
    status: 'idle',
    customersLastSynced: 0,
    invoicesLastSynced: 0,
    paymentsLastSynced: 0,
    errorsFound: 0,
    errorMessages: [],
    companyName: '',
    customersCount: 0,
    invoicesCount: 0,
    paymentsCount: 0,
    errors: [],
  },
  settings: {
    businessName: 'Pinnacle Home Services',
    phone: '(555) 400-7890',
    email: 'info@pinnaclehomeservices.com',
    address: '800 Commerce Drive, Springfield, IL 62701',
    website: 'www.pinnaclehomeservices.com',
    logo: '',
    teamMembers: ['Mike Rodriguez', 'Sarah Chen', 'Tom Baker', 'Dave Williams'],
    leadSources: ['Website', 'Google Ads', 'Facebook', 'Referral', 'Yard Sign', 'Door Hanger', 'Nextdoor', 'Yelp', 'Other'],
    serviceCategories: ['HVAC Installation', 'HVAC Repair', 'HVAC Maintenance', 'Plumbing', 'Electrical', 'Insulation', 'Generators'],
  },
};
